# Default values for mongodb-stash.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# we are declaring these values as global so that parent chart can overwrite them
docker:
  registry: appscode
  image: mongodb-stash
  tag: 3.6

# optional argument to send mgdump or psql command
backup:
  mgArgs: ""
restore:
  mgArgs: ""

# default values for prometheus metrics
metrics:
  enabled: true
  labels: []

# Maximum concurrency to perform backup or restore tasks
maxConcurrency: 3