apiVersion: v1
description: 'stash-mongodb - MongoDB database backup and restore plugin for Stash  by AppsCode'
name: stash-mongodb
version: "4.0.11"
appVersion: "4.0.11"
home: https://github.com/stashed/mongodb
icon: https://cdn.appscode.com/images/icon/stash.png
sources:
  - https://github.com/stashed/mongodb
maintainers:
  - name: appscode
    email: support@appscode.com
